org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false
org.gradle.java.home=C:/Program Files/Java/jdk-21



# Minecraft y NeoForge
minecraft_version=1.21.1
mc=1.21
neo_version=21.1.240
loader_version_range=[4,)

# Parchment
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
neogradle.subsystems.conventions.runs.create-default-run-per-type=false

# Dependencies
jei_version=19.27.0.340
jade_version=7428884
avaritia_version_id=7445860
appleskin_version=3.0.8
geckolib_version=4.9.2
patchouli_version=1.21.1-93-NEOFORGE
exdeorum_version=3.12
allthemodium_project_id=364466
allthemodium_version=7974403
modkit_version=1.1.0


# Mod Information
mod_id=ultimatefoods
mod_name=UltimateFoods 
mod_named=Ultimate Foods
mod_version=2.0.9
tag_lanzador=NeoForge
mod_group_id=nadiendev.ultimatefoods
mod_license=MIT
mod_authors=SrNadien
mod_description=Add Exra Foods , Items And More. 